// ─── i18n 国际化支持 ──────────────────────────────────────
// 简单的键值对翻译系统，支持中英文切换

export type Lang = 'zh' | 'en' | 'ar' | 'de' | 'es' | 'fr' | 'hi' | 'it' | 'ja' | 'ko' | 'nl' | 'pl' | 'pt' | 'ru' | 'th' | 'tr' | 'vi';

// 语言列表：zh/en 固定在前，分隔线后 17 种语言全部按原生名称 Unicode 排序（zh/en 重复出现）
export const PINNED_LANGS: Lang[] = ['zh', 'en'];

// 全部 17 种语言按原生名称 Unicode 码点排序
export const LANG_OPTIONS: { code: Lang; label: string }[] = [
  { code: 'ar', label: 'العربية' },
  { code: 'de', label: 'Deutsch' },
  { code: 'en', label: 'English' },
  { code: 'es', label: 'Español' },
  { code: 'fr', label: 'Français' },
  { code: 'hi', label: 'हिन्दी' },
  { code: 'it', label: 'Italiano' },
  { code: 'ja', label: '日本語' },
  { code: 'ko', label: '한국어' },
  { code: 'nl', label: 'Nederlands' },
  { code: 'pl', label: 'Polski' },
  { code: 'pt', label: 'Português' },
  { code: 'ru', label: 'Русский' },
  { code: 'th', label: 'ไทย' },
  { code: 'tr', label: 'Türkçe' },
  { code: 'vi', label: 'Tiếng Việt' },
  { code: 'zh', label: '简体中文' },
];

const translations: Record<string, Record<Lang, string>> = {
  // 通用
  'app.loading': { zh: '查询中…', en: 'Loading…', ja: 'Loading…', ko: 'Loading…', ar: 'Loading…', de: 'Loading…', es: 'Loading…', fr: 'Loading…', hi: 'Loading…', it: 'Loading…', nl: 'Loading…', pl: 'Loading…', pt: 'Loading…', ru: 'Loading…', th: 'Loading…', tr: 'Loading…', vi: 'Loading…' },
  'app.error': { zh: '查询失败', en: 'Query failed', ja: 'Query failed', ko: 'Query failed', ar: 'Query failed', de: 'Query failed', es: 'Query failed', fr: 'Query failed', hi: 'Query failed', it: 'Query failed', nl: 'Query failed', pl: 'Query failed', pt: 'Query failed', ru: 'Query failed', th: 'Query failed', tr: 'Query failed', vi: 'Query failed' },
  'app.unconfigured': { zh: '未配置', en: 'Not configured', ja: 'Not configured', ko: 'Not configured', ar: 'Not configured', de: 'Not configured', es: 'Not configured', fr: 'Not configured', hi: 'Not configured', it: 'Not configured', nl: 'Not configured', pl: 'Not configured', pt: 'Not configured', ru: 'Not configured', th: 'Not configured', tr: 'Not configured', vi: 'Not configured' },
  'app.unconfigured_token': { zh: '未配置 Token', en: 'Token not configured', ja: 'Token not configured', ko: 'Token not configured', ar: 'Token not configured', de: 'Token not configured', es: 'Token not configured', fr: 'Token not configured', hi: 'Token not configured', it: 'Token not configured', nl: 'Token not configured', pl: 'Token not configured', pt: 'Token not configured', ru: 'Token not configured', th: 'Token not configured', tr: 'Token not configured', vi: 'Token not configured' },
  'app.unavailable': { zh: '不可用', en: 'Unavailable', ja: 'Unavailable', ko: 'Unavailable', ar: 'Unavailable', de: 'Unavailable', es: 'Unavailable', fr: 'Unavailable', hi: 'Unavailable', it: 'Unavailable', nl: 'Unavailable', pl: 'Unavailable', pt: 'Unavailable', ru: 'Unavailable', th: 'Unavailable', tr: 'Unavailable', vi: 'Unavailable' },
  'app.no_data': { zh: '暂无数据', en: 'No data', ja: 'No data', ko: 'No data', ar: 'No data', de: 'No data', es: 'No data', fr: 'No data', hi: 'No data', it: 'No data', nl: 'No data', pl: 'No data', pt: 'No data', ru: 'No data', th: 'No data', tr: 'No data', vi: 'No data' },
  'app.tokens': { zh: 'tokens', en: 'tokens', ja: 'tokens', ko: 'tokens', ar: 'tokens', de: 'tokens', es: 'tokens', fr: 'tokens', hi: 'tokens', it: 'tokens', nl: 'tokens', pl: 'tokens', pt: 'tokens', ru: 'tokens', th: 'tokens', tr: 'tokens', vi: 'tokens' },

  // 余额
  'balance.title': { zh: '账户余额', en: 'Account Balance', ja: 'Account Balance', ko: 'Account Balance', ar: 'Account Balance', de: 'Account Balance', es: 'Account Balance', fr: 'Account Balance', hi: 'Account Balance', it: 'Account Balance', nl: 'Account Balance', pl: 'Account Balance', pt: 'Account Balance', ru: 'Account Balance', th: 'Account Balance', tr: 'Account Balance', vi: 'Account Balance' },
  'balance.available': { zh: '可用', en: 'Available', ja: 'Available', ko: 'Available', ar: 'Available', de: 'Available', es: 'Available', fr: 'Available', hi: 'Available', it: 'Available', nl: 'Available', pl: 'Available', pt: 'Available', ru: 'Available', th: 'Available', tr: 'Available', vi: 'Available' },
  'balance.insufficient': { zh: '余额不足', en: 'Insufficient', ja: 'Insufficient', ko: 'Insufficient', ar: 'Insufficient', de: 'Insufficient', es: 'Insufficient', fr: 'Insufficient', hi: 'Insufficient', it: 'Insufficient', nl: 'Insufficient', pl: 'Insufficient', pt: 'Insufficient', ru: 'Insufficient', th: 'Insufficient', tr: 'Insufficient', vi: 'Insufficient' },
  'balance.today': { zh: '当日消耗', en: 'Today', ja: 'Today', ko: 'Today', ar: 'Today', de: 'Today', es: 'Today', fr: 'Today', hi: 'Today', it: 'Today', nl: 'Today', pl: 'Today', pt: 'Today', ru: 'Today', th: 'Today', tr: 'Today', vi: 'Today' },
  'balance.monthly': { zh: '本月消费', en: 'This Month', ja: 'This Month', ko: 'This Month', ar: 'This Month', de: 'This Month', es: 'This Month', fr: 'This Month', hi: 'This Month', it: 'This Month', nl: 'This Month', pl: 'This Month', pt: 'This Month', ru: 'This Month', th: 'This Month', tr: 'This Month', vi: 'This Month' },

  // 设置
  'settings.title': { zh: '设置', en: 'Settings', ja: 'Settings', ko: 'Settings', ar: 'Settings', de: 'Settings', es: 'Settings', fr: 'Settings', hi: 'Settings', it: 'Settings', nl: 'Settings', pl: 'Settings', pt: 'Settings', ru: 'Settings', th: 'Settings', tr: 'Settings', vi: 'Settings' },
  'settings.api_key': { zh: 'API Key', en: 'API Key', ja: 'API Key', ko: 'API Key', ar: 'API Key', de: 'API Key', es: 'API Key', fr: 'API Key', hi: 'API Key', it: 'API Key', nl: 'API Key', pl: 'API Key', pt: 'API Key', ru: 'API Key', th: 'API Key', tr: 'API Key', vi: 'API Key' },
  'settings.api_key_desc': { zh: '用于调用 API 获取余额和用量数据。', en: 'Used to call API for balance and usage data.', ja: 'Used to call API for balance and usage data.', ko: 'Used to call API for balance and usage data.', ar: 'Used to call API for balance and usage data.', de: 'Used to call API for balance and usage data.', es: 'Used to call API for balance and usage data.', fr: 'Used to call API for balance and usage data.', hi: 'Used to call API for balance and usage data.', it: 'Used to call API for balance and usage data.', nl: 'Used to call API for balance and usage data.', pl: 'Used to call API for balance and usage data.', pt: 'Used to call API for balance and usage data.', ru: 'Used to call API for balance and usage data.', th: 'Used to call API for balance and usage data.', tr: 'Used to call API for balance and usage data.', vi: 'Used to call API for balance and usage data.' },
  'settings.save': { zh: '验证并保存', en: 'Verify & Save', ja: 'Verify & Save', ko: 'Verify & Save', ar: 'Verify & Save', de: 'Verify & Save', es: 'Verify & Save', fr: 'Verify & Save', hi: 'Verify & Save', it: 'Verify & Save', nl: 'Verify & Save', pl: 'Verify & Save', pt: 'Verify & Save', ru: 'Verify & Save', th: 'Verify & Save', tr: 'Verify & Save', vi: 'Verify & Save' },
  'settings.clear': { zh: '清除 Key', en: 'Clear Key', ja: 'Clear Key', ko: 'Clear Key', ar: 'Clear Key', de: 'Clear Key', es: 'Clear Key', fr: 'Clear Key', hi: 'Clear Key', it: 'Clear Key', nl: 'Clear Key', pl: 'Clear Key', pt: 'Clear Key', ru: 'Clear Key', th: 'Clear Key', tr: 'Clear Key', vi: 'Clear Key' },
  'settings.verified': { zh: '已配置', en: 'Configured', ja: 'Configured', ko: 'Configured', ar: 'Configured', de: 'Configured', es: 'Configured', fr: 'Configured', hi: 'Configured', it: 'Configured', nl: 'Configured', pl: 'Configured', pt: 'Configured', ru: 'Configured', th: 'Configured', tr: 'Configured', vi: 'Configured' },
  'settings.not_configured': { zh: '未配置', en: 'Not configured', ja: 'Not configured', ko: 'Not configured', ar: 'Not configured', de: 'Not configured', es: 'Not configured', fr: 'Not configured', hi: 'Not configured', it: 'Not configured', nl: 'Not configured', pl: 'Not configured', pt: 'Not configured', ru: 'Not configured', th: 'Not configured', tr: 'Not configured', vi: 'Not configured' },
  'settings.general': { zh: '通用', en: 'General', ja: 'General', ko: 'General', ar: 'General', de: 'General', es: 'General', fr: 'General', hi: 'General', it: 'General', nl: 'General', pl: 'General', pt: 'General', ru: 'General', th: 'General', tr: 'General', vi: 'General' },
  'settings.autostart': { zh: '开机自启', en: 'Auto Start', ja: 'Auto Start', ko: 'Auto Start', ar: 'Auto Start', de: 'Auto Start', es: 'Auto Start', fr: 'Auto Start', hi: 'Auto Start', it: 'Auto Start', nl: 'Auto Start', pl: 'Auto Start', pt: 'Auto Start', ru: 'Auto Start', th: 'Auto Start', tr: 'Auto Start', vi: 'Auto Start' },
  'settings.autostart_desc': { zh: '开启后，每次登录 Windows 时自动启动应用。', en: 'Auto start on Windows login.', ja: 'Auto start on Windows login.', ko: 'Auto start on Windows login.', ar: 'Auto start on Windows login.', de: 'Auto start on Windows login.', es: 'Auto start on Windows login.', fr: 'Auto start on Windows login.', hi: 'Auto start on Windows login.', it: 'Auto start on Windows login.', nl: 'Auto start on Windows login.', pl: 'Auto start on Windows login.', pt: 'Auto start on Windows login.', ru: 'Auto start on Windows login.', th: 'Auto start on Windows login.', tr: 'Auto start on Windows login.', vi: 'Auto start on Windows login.' },
  'settings.auto_refresh': { zh: '自动刷新', en: 'Auto Refresh', ja: 'Auto Refresh', ko: 'Auto Refresh', ar: 'Auto Refresh', de: 'Auto Refresh', es: 'Auto Refresh', fr: 'Auto Refresh', hi: 'Auto Refresh', it: 'Auto Refresh', nl: 'Auto Refresh', pl: 'Auto Refresh', pt: 'Auto Refresh', ru: 'Auto Refresh', th: 'Auto Refresh', tr: 'Auto Refresh', vi: 'Auto Refresh' },
  'settings.auto_refresh_desc': { zh: '开启后，按设定周期自动拉取最新数据。', en: 'Automatically fetch latest data at set intervals.', ja: 'Automatically fetch latest data at set intervals.', ko: 'Automatically fetch latest data at set intervals.', ar: 'Automatically fetch latest data at set intervals.', de: 'Automatically fetch latest data at set intervals.', es: 'Automatically fetch latest data at set intervals.', fr: 'Automatically fetch latest data at set intervals.', hi: 'Automatically fetch latest data at set intervals.', it: 'Automatically fetch latest data at set intervals.', nl: 'Automatically fetch latest data at set intervals.', pl: 'Automatically fetch latest data at set intervals.', pt: 'Automatically fetch latest data at set intervals.', ru: 'Automatically fetch latest data at set intervals.', th: 'Automatically fetch latest data at set intervals.', tr: 'Automatically fetch latest data at set intervals.', vi: 'Automatically fetch latest data at set intervals.' },
  'settings.window_size': { zh: '窗口大小', en: 'Window Size', ja: 'Window Size', ko: 'Window Size', ar: 'Window Size', de: 'Window Size', es: 'Window Size', fr: 'Window Size', hi: 'Window Size', it: 'Window Size', nl: 'Window Size', pl: 'Window Size', pt: 'Window Size', ru: 'Window Size', th: 'Window Size', tr: 'Window Size', vi: 'Window Size' },
  'settings.window_desc': { zh: '选择预设窗口尺寸，或拖拽窗口边缘自由调整。', en: 'Choose a preset size or drag window edges.', ja: 'Choose a preset size or drag window edges.', ko: 'Choose a preset size or drag window edges.', ar: 'Choose a preset size or drag window edges.', de: 'Choose a preset size or drag window edges.', es: 'Choose a preset size or drag window edges.', fr: 'Choose a preset size or drag window edges.', hi: 'Choose a preset size or drag window edges.', it: 'Choose a preset size or drag window edges.', nl: 'Choose a preset size or drag window edges.', pl: 'Choose a preset size or drag window edges.', pt: 'Choose a preset size or drag window edges.', ru: 'Choose a preset size or drag window edges.', th: 'Choose a preset size or drag window edges.', tr: 'Choose a preset size or drag window edges.', vi: 'Choose a preset size or drag window edges.' },
  'settings.compact': { zh: '紧凑', en: 'Compact', ja: 'Compact', ko: 'Compact', ar: 'Compact', de: 'Compact', es: 'Compact', fr: 'Compact', hi: 'Compact', it: 'Compact', nl: 'Compact', pl: 'Compact', pt: 'Compact', ru: 'Compact', th: 'Compact', tr: 'Compact', vi: 'Compact' },
  'settings.standard': { zh: '标准', en: 'Standard', ja: 'Standard', ko: 'Standard', ar: 'Standard', de: 'Standard', es: 'Standard', fr: 'Standard', hi: 'Standard', it: 'Standard', nl: 'Standard', pl: 'Standard', pt: 'Standard', ru: 'Standard', th: 'Standard', tr: 'Standard', vi: 'Standard' },
  'settings.wide': { zh: '宽屏', en: 'Wide', ja: 'Wide', ko: 'Wide', ar: 'Wide', de: 'Wide', es: 'Wide', fr: 'Wide', hi: 'Wide', it: 'Wide', nl: 'Wide', pl: 'Wide', pt: 'Wide', ru: 'Wide', th: 'Wide', tr: 'Wide', vi: 'Wide' },
  'settings.large': { zh: '大屏', en: 'Large', ja: 'Large', ko: 'Large', ar: 'Large', de: 'Large', es: 'Large', fr: 'Large', hi: 'Large', it: 'Large', nl: 'Large', pl: 'Large', pt: 'Large', ru: 'Large', th: 'Large', tr: 'Large', vi: 'Large' },
  'settings.about': { zh: '关于', en: 'About', ja: 'About', ko: 'About', ar: 'About', de: 'About', es: 'About', fr: 'About', hi: 'About', it: 'About', nl: 'About', pl: 'About', pt: 'About', ru: 'About', th: 'About', tr: 'About', vi: 'About' },
  'settings.version': { zh: '当前版本', en: 'Version', ja: 'Version', ko: 'Version', ar: 'Version', de: 'Version', es: 'Version', fr: 'Version', hi: 'Version', it: 'Version', nl: 'Version', pl: 'Version', pt: 'Version', ru: 'Version', th: 'Version', tr: 'Version', vi: 'Version' },
  'settings.check_update': { zh: '检查更新', en: 'Check for Updates', ja: 'Check for Updates', ko: 'Check for Updates', ar: 'Check for Updates', de: 'Check for Updates', es: 'Check for Updates', fr: 'Check for Updates', hi: 'Check for Updates', it: 'Check for Updates', nl: 'Check for Updates', pl: 'Check for Updates', pt: 'Check for Updates', ru: 'Check for Updates', th: 'Check for Updates', tr: 'Check for Updates', vi: 'Check for Updates' },
  'settings.checking': { zh: '检查中…', en: 'Checking…', ja: 'Checking…', ko: 'Checking…', ar: 'Checking…', de: 'Checking…', es: 'Checking…', fr: 'Checking…', hi: 'Checking…', it: 'Checking…', nl: 'Checking…', pl: 'Checking…', pt: 'Checking…', ru: 'Checking…', th: 'Checking…', tr: 'Checking…', vi: 'Checking…' },
  'settings.latest': { zh: '已是最新版本', en: 'Up to date', ja: 'Up to date', ko: 'Up to date', ar: 'Up to date', de: 'Up to date', es: 'Up to date', fr: 'Up to date', hi: 'Up to date', it: 'Up to date', nl: 'Up to date', pl: 'Up to date', pt: 'Up to date', ru: 'Up to date', th: 'Up to date', tr: 'Up to date', vi: 'Up to date' },
  'settings.update_found': { zh: '发现新版本', en: 'Update available', ja: 'Update available', ko: 'Update available', ar: 'Update available', de: 'Update available', es: 'Update available', fr: 'Update available', hi: 'Update available', it: 'Update available', nl: 'Update available', pl: 'Update available', pt: 'Update available', ru: 'Update available', th: 'Update available', tr: 'Update available', vi: 'Update available' },
  'settings.download_update': { zh: '下载更新', en: 'Download Update', ja: 'アップデートをダウンロード', ko: '업데이트 다운로드', ar: 'تحديث التنزيل', de: 'Update herunterladen', es: 'Descargar actualización', fr: 'Télécharger la mise à jour', hi: 'अपडेट डाउनलोड करें', it: 'Scarica aggiornamento', nl: 'Update downloaden', pl: 'Pobierz aktualizację', pt: 'Baixar atualização', ru: 'Скачать обновление', th: 'ดาวน์โหลดอัปเดต', tr: 'Güncellemeyi İndir', vi: 'Tải bản cập nhật' },
  'settings.downloading_update': { zh: '下载中…', en: 'Downloading…', ja: 'ダウンロード中…', ko: '다운로드 중…', ar: 'جارٍ التنزيل…', de: 'Wird heruntergeladen…', es: 'Descargando…', fr: 'Téléchargement…', hi: 'डाउनलोड हो रहा है…', it: 'Download in corso…', nl: 'Downloaden…', pl: 'Pobieranie…', pt: 'Baixando…', ru: 'Загрузка…', th: 'กำลังดาวน์โหลด…', tr: 'İndiriliyor…', vi: 'Đang tải xuống…' },
  'settings.update_installed': { zh: '更新已安装，即将重启', en: 'Update installed, restarting…', ja: 'アップデートがインストールされました、再起動中…', ko: '업데이트 설치됨, 재시작 중…', ar: 'تم تثبيت التحديث، إعادة التشغيل…', de: 'Update installiert, Neustart…', es: 'Actualización instalada, reiniciando…', fr: 'Mise à jour installée, redémarrage…', hi: 'अपडेट इंस्टॉल हो गया, पुनरारंभ हो रहा है…', it: 'Aggiornamento installato, riavvio…', nl: 'Update geïnstalleerd, herstarten…', pl: 'Aktualizacja zainstalowana, ponowne uruchamianie…', pt: 'Atualização instalada, reiniciando…', ru: 'Обновление установлено, перезапуск…', th: 'ติดตั้งอัปเดตแล้ว กำลังรีสตาร์ท…', tr: 'Güncelleme yüklendi, yeniden başlatılıyor…', vi: 'Đã cài đặt bản cập nhật, đang khởi động lại…' },
  'settings.theme': { zh: '主题', en: 'Theme', ja: 'テーマ', ko: '테마', ar: 'المظهر', de: 'Design', es: 'Tema', fr: 'Thème', hi: 'थीम', it: 'Tema', nl: 'Thema', pl: 'Motyw', pt: 'Tema', ru: 'Тема', th: 'ธีม', tr: 'Tema', vi: 'Giao diện' },
  'settings.theme_light': { zh: '浅色', en: 'Light', ja: 'ライト', ko: '라이트', ar: 'فاتح', de: 'Hell', es: 'Claro', fr: 'Clair', hi: 'लाइट', it: 'Chiaro', nl: 'Licht', pl: 'Jasny', pt: 'Claro', ru: 'Светлая', th: 'สว่าง', tr: 'Açık', vi: 'Sáng' },
  'settings.theme_dark': { zh: '深色', en: 'Dark', ja: 'ダーク', ko: '다크', ar: 'داكن', de: 'Dunkel', es: 'Oscuro', fr: 'Sombre', hi: 'डार्क', it: 'Scuro', nl: 'Donker', pl: 'Ciemny', pt: 'Escuro', ru: 'Тёмная', th: 'มืด', tr: 'Koyu', vi: 'Tối' },
  'settings.theme_system': { zh: '跟随系统', en: 'System', ja: 'システム', ko: '시스템', ar: 'النظام', de: 'System', es: 'Sistema', fr: 'Système', hi: 'सिस्टम', it: 'Sistema', nl: 'Systeem', pl: 'System', pt: 'Sistema', ru: 'Системная', th: 'ระบบ', tr: 'Sistem', vi: 'Hệ thống' },
  'settings.currency': { zh: '货币单位', en: 'Currency', ja: '通貨', ko: '통화', ar: 'العملة', de: 'Währung', es: 'Moneda', fr: 'Devise', hi: 'मुद्रा', it: 'Valuta', nl: 'Valuta', pl: 'Waluta', pt: 'Moeda', ru: 'Валюта', th: 'สกุลเงิน', tr: 'Para birimi', vi: 'Tiền tệ' },
  'settings.currency_cny': { zh: '人民币 (¥)', en: 'CNY (¥)', ja: '人民元 (¥)', ko: 'CNY (¥)', ar: 'يوان (¥)', de: 'CNY (¥)', es: 'CNY (¥)', fr: 'CNY (¥)', hi: 'CNY (¥)', it: 'CNY (¥)', nl: 'CNY (¥)', pl: 'CNY (¥)', pt: 'CNY (¥)', ru: 'CNY (¥)', th: 'CNY (¥)', tr: 'CNY (¥)', vi: 'CNY (¥)' },
  'settings.currency_usd': { zh: '美元 ($)', en: 'USD ($)', ja: 'ドル ($)', ko: 'USD ($)', ar: 'دولار ($)', de: 'USD ($)', es: 'USD ($)', fr: 'USD ($)', hi: 'USD ($)', it: 'USD ($)', nl: 'USD ($)', pl: 'USD ($)', pt: 'USD ($)', ru: 'USD ($)', th: 'USD ($)', tr: 'USD ($)', vi: 'USD ($)' },
  'settings.currency_mt': { zh: '百万Token/¥', en: 'MT/¥', ja: 'MT/¥', ko: 'MT/¥', ar: 'MT/¥', de: 'MT/¥', es: 'MT/¥', fr: 'MT/¥', hi: 'MT/¥', it: 'MT/¥', nl: 'MT/¥', pl: 'MT/¥', pt: 'MT/¥', ru: 'MT/¥', th: 'MT/¥', tr: 'MT/¥', vi: 'MT/¥' },
  'settings.cat_account': { zh: '账户', en: 'Account', ja: 'アカウント', ko: '계정', ar: 'الحساب', de: 'Konto', es: 'Cuenta', fr: 'Compte', hi: 'खाता', it: 'Account', nl: 'Account', pl: 'Konto', pt: 'Conta', ru: 'Аккаунт', th: 'บัญชี', tr: 'Hesap', vi: 'Tài khoản' },
  'settings.cat_general': { zh: '通用', en: 'General', ja: '一般', ko: '일반', ar: 'عام', de: 'Allgemein', es: 'General', fr: 'Général', hi: 'सामान्य', it: 'Generale', nl: 'Algemeen', pl: 'Ogólne', pt: 'Geral', ru: 'Общие', th: 'ทั่วไป', tr: 'Genel', vi: 'Chung' },
  'settings.cat_display': { zh: '显示', en: 'Display', ja: '表示', ko: '표시', ar: 'العرض', de: 'Anzeige', es: 'Pantalla', fr: 'Affichage', hi: 'प्रदर्शन', it: 'Display', nl: 'Weergave', pl: 'Wyświetlanie', pt: 'Exibição', ru: 'Отображение', th: 'แสดงผล', tr: 'Görüntü', vi: 'Hiển thị' },
  'settings.cat_about': { zh: '关于', en: 'About', ja: 'について', ko: '정보', ar: 'حول', de: 'Über', es: 'Acerca de', fr: 'À propos', hi: 'के बारे में', it: 'Informazioni', nl: 'Over', pl: 'O programie', pt: 'Sobre', ru: 'О программе', th: 'เกี่ยวกับ', tr: 'Hakkında', vi: 'Giới thiệu' },
  'settings.cat_data': { zh: '数据管理', en: 'Data', ja: 'データ', ko: '데이터', ar: 'البيانات', de: 'Daten', es: 'Datos', fr: 'Données', hi: 'डेटा', it: 'Dati', nl: 'Gegevens', pl: 'Dane', pt: 'Dados', ru: 'Данные', th: 'ข้อมูล', tr: 'Veri', vi: 'Dữ liệu' },
  'settings.cat_advanced': { zh: '高级', en: 'Advanced', ja: '詳細設定', ko: '고급', ar: 'متقدم', de: 'Erweitert', es: 'Avanzado', fr: 'Avancé', hi: 'उन्नत', it: 'Avanzate', nl: 'Geavanceerd', pl: 'Zaawansowane', pt: 'Avançado', ru: 'Дополнительно', th: 'ขั้นสูง', tr: 'Gelişmiş', vi: 'Nâng cao' },
  'settings.default_provider': { zh: '默认启动平台', en: 'Default Platform', ja: 'デフォルトプラットフォーム', ko: '기본 플랫폼', ar: 'المنصة الافتراضية', de: 'Standardplattform', es: 'Plataforma predeterminada', fr: 'Plateforme par défaut', hi: 'डिफ़ॉल्ट प्लेटफ़ॉर्म', it: 'Piattaforma predefinita', nl: 'Standaardplatform', pl: 'Domyślna platforma', pt: 'Plataforma padrão', ru: 'Платформа по умолчанию', th: 'แพลตฟอร์มเริ่มต้น', tr: 'Varsayılan Platform', vi: 'Nền tảng mặc định' },
  'settings.mimo_interval': { zh: 'MiMo 查询间隔', en: 'MiMo Refresh Interval', ja: 'MiMo更新間隔', ko: 'MiMo 새로고침 간격', ar: 'فاصل تحديث MiMo', de: 'MiMo-Aktualisierungsintervall', es: 'Intervalo de actualización MiMo', fr: 'Intervalle de rafraîchissement MiMo', hi: 'MiMo रिफ्रेश अंतराल', it: 'Intervalo di aggiornamento MiMo', nl: 'MiMo vernieuwingsinterval', pl: 'Interwał odświeżania MiMo', pt: 'Intervalo de atualização MiMo', ru: 'Интервал обновления MiMo', th: 'ช่วงเวลาอัปเดต MiMo', tr: 'MiMo Yenileme Aralığı', vi: 'Khoảng thời gian làm mới MiMo' },
  'settings.mimo_interval_desc': { zh: 'MiMo 查询比 DeepSeek 慢，建议设置较长间隔。设为 0 则使用全局间隔。', en: 'MiMo queries are slower than DeepSeek. Set to 0 to use global interval.', ja: 'MiMo のクエリは DeepSeek より遅いため、長めの間隔を推奨。0 でグローバル間隔を使用。', ko: 'MiMo 쿼리는 DeepSeek보다 느릅니다. 0이면 전역 간격을 사용합니다.', ar: 'استعلامات MiMo أبطأ من DeepSeek. اضبط على 0 لاستخدام الفاصل الزمني العام.', de: 'MiMo-Abfragen sind langsamer als DeepSeek. 0 für globales Intervall.', es: 'Las consultas de MiMo son más lentas que DeepSeek. 0 para usar intervalo global.', fr: 'Les requêtes MiMo sont plus lentes que DeepSeek. 0 pour utiliser l\'intervalle global.', hi: 'MiMo क्वेरी DeepSeek से धीमी है। ग्लोबल अंतराल के लिए 0 सेट करें।', it: 'Le query MiMo sono più lente di DeepSeek. Imposta 0 per usare l\'intervallo globale.', nl: 'MiMo queries zijn langzamer dan DeepSeek. Stel in op 0 voor globaal interval.', pl: 'Zapytania MiMo są wolniejsze niż DeepSeek. Ustaw 0 dla globalnego interwału.', pt: 'Consultas MiMo são mais lentas que DeepSeek. Defina 0 para usar intervalo global.', ru: 'Запросы MiMo медленнее DeepSeek. Установите 0 для глобального интервала.', th: 'แบบสอบถาม MiMo ช้ากว่า DeepSeek ตั้งค่า 0 เพื่อใช้ช่วงเวลาทั่วไป', tr: 'MiMo sorguları DeepSeek\'ten yavaştır. Genel aralık için 0 ayarlayın.', vi: 'Truy vấn MiMo chậm hơn DeepSeek. Đặt 0 để sử dụng khoảng thời gian toàn cục.' },
  'settings.notify_cooldown': { zh: '通知冷却时间', en: 'Notification Cooldown', ja: '通知クールダウン', ko: '알림 쿨다운', ar: 'فترة تهدئة الإشعارات', de: 'Benachrichtigungs-Cooldown', es: 'Enfriamiento de notificaciones', fr: 'Délai de refroidissement des notifications', hi: 'सूचना कूलडाउन', it: 'Raffreddamento notifiche', nl: 'Meldingscooldown', pl: 'Schłodzenie powiadomień', pt: 'Resfriamento de notificações', ru: 'Перерыв между уведомлениями', th: 'คูลดาวน์การแจ้งเตือน', tr: 'Bildirim Bekleme Süresi', vi: 'Thời gian chờ thông báo' },
  'settings.notify_cooldown_desc': { zh: '避免短时间内重复弹窗，单位为分钟。', en: 'Avoid repeated notifications in a short time, in minutes.', ja: '短時間内の繰り返し通知を防ぎます（分単位）。', ko: '짧은 시간 내 반복 알림을 방지합니다(분 단위).', ar: 'تجنب تكرار الإشعارات في وقت قصير بالدقائق.', de: 'Wiederholte Benachrichtigungen in kurzer Zeit vermeiden, in Minuten.', es: 'Evitar notificaciones repetidas en un corto período, en minutos.', fr: 'Éviter les notifications répétées en peu de temps, en minutes.', hi: 'कम समय में दोहराई गई सूचनाओं से बचें, मिनटों में।', it: 'Evita notifiche ripetute in poco tempo, in minuti.', nl: 'Vermijd herhaalde meldingen in korte tijd, in minuten.', pl: 'Unikaj powtarzających się powiadomień w krótkim czasie, w minutach.', pt: 'Evitar notificações repetidas em pouco tempo, em minutos.', ru: 'Избегайте повторных уведомлений за короткое время, в минутах.', th: 'หลีกเลี่ยงการแจ้งเตือนซ้ำในเวลาอันสั้น เป็นนาที', tr: 'Kısa sürede tekrarlayan bildirimleri önleyin, dakika cinsinden.', vi: 'Tránh lặp lại thông báo trong thời gian ngắn, tính bằng phút.' },
  'settings.clear_cache': { zh: '清除所有缓存数据', en: 'Clear All Cache', ja: 'キャッシュをクリア', ko: '캐시 지우기', ar: 'مسح جميع بيانات التخزين المؤقت', de: 'Alle Cache-Daten löschen', es: 'Borrar todos los datos de caché', fr: 'Effacer toutes les données du cache', hi: 'सभी कैश डेटा साफ़ करें', it: 'Cancella tutti i dati della cache', nl: 'Alle cachegegevens wissen', pl: 'Wyczyść wszystkie dane cache', pt: 'Limpar todos os dados do cache', ru: 'Очистить все данные кэша', th: 'ล้างข้อมูลแคชทั้งหมด', tr: 'Tüm önbellek verilerini temizle', vi: 'Xóa tất cả dữ liệu bộ nhớ đệm' },
  'settings.clear_cache_desc': { zh: '清除 localStorage 中的缓存数据，不影响配置文件和登录状态。', en: 'Clear cached data in localStorage. Config and login state are preserved.', ja: 'localStorageのキャッシュデータを削除します。設定とログイン状態は保持されます。', ko: 'localStorage의 캐시 데이터를 삭제합니다. 설정과 로그인 상태는 유지됩니다.', ar: 'مسح البيانات المخزنة مؤقتاً في localStorage. يتم الحفاظ على التكوين وحالة تسجيل الدخول.', de: 'Cache-Daten in localStorage löschen. Konfiguration und Anmeldestatus bleiben erhalten.', es: 'Borrar datos en caché en localStorage. La configuración y el estado de inicio de sesión se conservan.', fr: 'Effacer les données en cache dans localStorage. La configuration et l\'état de connexion sont conservés.', hi: 'localStorage में कैश डेटा साफ़ करें। कॉन्फ़िगरेशन और लॉगिन स्थिति संरक्षित हैं।', it: 'Cancella i dati nella cache di localStorage. Configurazione e stato di accesso sono preservati.', nl: 'Cachegegevens in localStorage wissen. Configuratie en loginstatus blijven behouden.', pl: 'Wyczyść dane cache w localStorage. Konfiguracja i stan logowania są zachowane.', pt: 'Limpar dados em cache no localStorage. Configuração e estado de login são preservados.', ru: 'Очистить кэшированные данные в localStorage. Конфигурация и состояние входа сохраняются.', th: 'ล้างข้อมูลแคชใน localStorage การกำหนดค่าและสถานะการเข้าสู่ระบบจะถูกเก็บไว้', tr: 'localStorage\'daki önbellek verilerini temizle. Yapılandırma ve oturum durumu korunur.', vi: 'Xóa dữ liệu bộ nhớ đệm trong localStorage. Cấu hình và trạng thái đăng nhập được giữ nguyên.' },
  'settings.export_config': { zh: '导出配置', en: 'Export Config', ja: '設定をエクスポート', ko: '설정 내보내기', ar: 'تصدير التكوين', de: 'Konfiguration exportieren', es: 'Exportar configuración', fr: 'Exporter la configuration', hi: 'कॉन्फ़िगरेशन निर्यात करें', it: 'Esporta configurazione', nl: 'Configuratie exporteren', pl: 'Eksportuj konfigurację', pt: 'Exportar configuração', ru: 'Экспорт конфигурации', th: 'ส่งออกการกำหนดค่า', tr: 'Yapılandırmayı dışa aktar', vi: 'Xuất cấu hình' },
  'settings.import_config': { zh: '导入配置', en: 'Import Config', ja: '設定をインポート', ko: '설정 가져오기', ar: 'استيراد التكوين', de: 'Konfiguration importieren', es: 'Importar configuración', fr: 'Importer la configuration', hi: 'कॉन्फ़िगरेशन आयात करें', it: 'Importa configurazione', nl: 'Configuratie importeren', pl: 'Importuj konfigurację', pt: 'Importar configuração', ru: 'Импорт конфигурации', th: 'นำเข้าการกำหนดค่า', tr: 'Yapılandırmayı içe aktar', vi: 'Nhập cấu hình' },
  'settings.webview_devtools': { zh: 'WebView 开发者工具', en: 'WebView DevTools', ja: 'WebView開発者ツール', ko: 'WebView 개발자 도구', ar: 'أدوات مطوري WebView', de: 'WebView-Entwicklertools', es: 'Herramientas de desarrollo WebView', fr: 'Outils de développement WebView', hi: 'WebView डेवलपर टूल्स', it: 'Strumenti sviluppatore WebView', nl: 'WebView-ontwikkeltools', pl: 'Narzędzia deweloperskie WebView', pt: 'Ferramentas de desenvolvimento WebView', ru: 'Инструменты разработчика WebView', th: 'เครื่องมือนักพัฒนา WebView', tr: 'WebView Geliştirici Araçları', vi: 'Công cụ phát triển WebView' },
  'settings.webview_devtools_desc': { zh: '开启后可在 MiMo WebView 中打开开发者工具。', en: 'Enable to open DevTools in the MiMo WebView.', ja: '有効にするとMiMo WebViewで開発者ツールを開けます。', ko: '활성화하면 MiMo WebView에서 개발자 도구를 열 수 있습니다.', ar: 'تمكين فتح أدوات المطور في WebView الخاص بـ MiMo.', de: 'Aktivieren, um Entwicklertools in der MiMo-WebView zu öffnen.', es: 'Habilite para abrir las herramientas de desarrollo en la WebView de MiMo.', fr: 'Activer pour ouvrir les outils de développement dans la WebView MiMo.', hi: 'MiMo WebView में डेवलपर टूल्स खोलने के लिए सक्षम करें।', it: 'Abilita per aprire gli strumenti di sviluppo nella WebView MiMo.', nl: 'Inschakelen om ontwikkeltools in de MiMo-WebView te openen.', pl: 'Włącz, aby otworzyć narzędzia deweloperskie w WebView MiMo.', pt: 'Ative para abrir ferramentas de desenvolvimento no WebView MiMo.', ru: 'Включите, чтобы открыть инструменты разработчика в WebView MiMo.', th: 'เปิดใช้งานเพื่อเปิดเครื่องมือนักพัฒนาใน WebView MiMo', tr: 'MiMo WebView\'de geliştirici araçlarını açmak için etkinleştirin.', vi: 'Bật để mở công cụ phát triển trong WebView MiMo.' },
  'settings.i18n_mt': { zh: '百万Token', en: 'MT', ja: 'MT', ko: 'MT', ar: 'MT', de: 'MT', es: 'MT', fr: 'MT', hi: 'MT', it: 'MT', nl: 'MT', pl: 'MT', pt: 'MT', ru: 'MT', th: 'MT', tr: 'MT', vi: 'MT' },
  'settings.i18n_per': { zh: '/', en: '/', ja: '/', ko: '/', ar: '/', de: '/', es: '/', fr: '/', hi: '/', it: '/', nl: '/', pl: '/', pt: '/', ru: '/', th: '/', tr: '/', vi: '/' },
  'settings.download': { zh: '请前往 GitHub Releases 下载最新安装包。', en: 'Please download from GitHub Releases.', ja: 'Please download from GitHub Releases.', ko: 'Please download from GitHub Releases.', ar: 'Please download from GitHub Releases.', de: 'Please download from GitHub Releases.', es: 'Please download from GitHub Releases.', fr: 'Please download from GitHub Releases.', hi: 'Please download from GitHub Releases.', it: 'Please download from GitHub Releases.', nl: 'Please download from GitHub Releases.', pl: 'Please download from GitHub Releases.', pt: 'Please download from GitHub Releases.', ru: 'Please download from GitHub Releases.', th: 'Please download from GitHub Releases.', tr: 'Please download from GitHub Releases.', vi: 'Please download from GitHub Releases.' },

  // 余额提醒
  'notify.title': { zh: '余额提醒', en: 'Balance Alert', ja: 'Balance Alert', ko: 'Balance Alert', ar: 'Balance Alert', de: 'Balance Alert', es: 'Balance Alert', fr: 'Balance Alert', hi: 'Balance Alert', it: 'Balance Alert', nl: 'Balance Alert', pl: 'Balance Alert', pt: 'Balance Alert', ru: 'Balance Alert', th: 'Balance Alert', tr: 'Balance Alert', vi: 'Balance Alert' },
  'notify.toggle': { zh: '低余额通知', en: 'Low Balance Alert', ja: 'Low Balance Alert', ko: 'Low Balance Alert', ar: 'Low Balance Alert', de: 'Low Balance Alert', es: 'Low Balance Alert', fr: 'Low Balance Alert', hi: 'Low Balance Alert', it: 'Low Balance Alert', nl: 'Low Balance Alert', pl: 'Low Balance Alert', pt: 'Low Balance Alert', ru: 'Low Balance Alert', th: 'Low Balance Alert', tr: 'Low Balance Alert', vi: 'Low Balance Alert' },
  'notify.desc': { zh: '当账户余额低于设定阈值时，弹出 Windows 通知提醒。默认关闭。', en: 'Show Windows notification when balance is below threshold. Off by default.', ja: 'Show Windows notification when balance is below threshold. Off by default.', ko: 'Show Windows notification when balance is below threshold. Off by default.', ar: 'Show Windows notification when balance is below threshold. Off by default.', de: 'Show Windows notification when balance is below threshold. Off by default.', es: 'Show Windows notification when balance is below threshold. Off by default.', fr: 'Show Windows notification when balance is below threshold. Off by default.', hi: 'Show Windows notification when balance is below threshold. Off by default.', it: 'Show Windows notification when balance is below threshold. Off by default.', nl: 'Show Windows notification when balance is below threshold. Off by default.', pl: 'Show Windows notification when balance is below threshold. Off by default.', pt: 'Show Windows notification when balance is below threshold. Off by default.', ru: 'Show Windows notification when balance is below threshold. Off by default.', th: 'Show Windows notification when balance is below threshold. Off by default.', tr: 'Show Windows notification when balance is below threshold. Off by default.', vi: 'Show Windows notification when balance is below threshold. Off by default.' },
  'notify.threshold': { zh: '阈值', en: 'Threshold', ja: 'Threshold', ko: 'Threshold', ar: 'Threshold', de: 'Threshold', es: 'Threshold', fr: 'Threshold', hi: 'Threshold', it: 'Threshold', nl: 'Threshold', pl: 'Threshold', pt: 'Threshold', ru: 'Threshold', th: 'Threshold', tr: 'Threshold', vi: 'Threshold' },

  // DeepSeek 用量同步
  'usage.title': { zh: '用量同步 Token', en: 'Usage Sync Token', ja: 'Usage Sync Token', ko: 'Usage Sync Token', ar: 'Usage Sync Token', de: 'Usage Sync Token', es: 'Usage Sync Token', fr: 'Usage Sync Token', hi: 'Usage Sync Token', it: 'Usage Sync Token', nl: 'Usage Sync Token', pl: 'Usage Sync Token', pt: 'Usage Sync Token', ru: 'Usage Sync Token', th: 'Usage Sync Token', tr: 'Usage Sync Token', vi: 'Usage Sync Token' },
  'usage.desc': { zh: '用于同步 Token 用量、消费和趋势图。需网页登录 token。', en: 'Sync token usage and trends. Requires web login token.', ja: 'Sync token usage and trends. Requires web login token.', ko: 'Sync token usage and trends. Requires web login token.', ar: 'Sync token usage and trends. Requires web login token.', de: 'Sync token usage and trends. Requires web login token.', es: 'Sync token usage and trends. Requires web login token.', fr: 'Sync token usage and trends. Requires web login token.', hi: 'Sync token usage and trends. Requires web login token.', it: 'Sync token usage and trends. Requires web login token.', nl: 'Sync token usage and trends. Requires web login token.', pl: 'Sync token usage and trends. Requires web login token.', pt: 'Sync token usage and trends. Requires web login token.', ru: 'Sync token usage and trends. Requires web login token.', th: 'Sync token usage and trends. Requires web login token.', tr: 'Sync token usage and trends. Requires web login token.', vi: 'Sync token usage and trends. Requires web login token.' },
  'usage.auto_sync': { zh: '网页登录自动同步', en: 'Web Login Auto Sync', ja: 'Web Login Auto Sync', ko: 'Web Login Auto Sync', ar: 'Web Login Auto Sync', de: 'Web Login Auto Sync', es: 'Web Login Auto Sync', fr: 'Web Login Auto Sync', hi: 'Web Login Auto Sync', it: 'Web Login Auto Sync', nl: 'Web Login Auto Sync', pl: 'Web Login Auto Sync', pt: 'Web Login Auto Sync', ru: 'Web Login Auto Sync', th: 'Web Login Auto Sync', tr: 'Web Login Auto Sync', vi: 'Web Login Auto Sync' },
  'usage.waiting': { zh: '等待登录', en: 'Waiting for login', ja: 'Waiting for login', ko: 'Waiting for login', ar: 'Waiting for login', de: 'Waiting for login', es: 'Waiting for login', fr: 'Waiting for login', hi: 'Waiting for login', it: 'Waiting for login', nl: 'Waiting for login', pl: 'Waiting for login', pt: 'Waiting for login', ru: 'Waiting for login', th: 'Waiting for login', tr: 'Waiting for login', vi: 'Waiting for login' },
  'usage.manual': { zh: '方式二：手动粘贴 token', en: 'Method 2: Paste token manually', ja: 'Method 2: Paste token manually', ko: 'Method 2: Paste token manually', ar: 'Method 2: Paste token manually', de: 'Method 2: Paste token manually', es: 'Method 2: Paste token manually', fr: 'Method 2: Paste token manually', hi: 'Method 2: Paste token manually', it: 'Method 2: Paste token manually', nl: 'Method 2: Paste token manually', pl: 'Method 2: Paste token manually', pt: 'Method 2: Paste token manually', ru: 'Method 2: Paste token manually', th: 'Method 2: Paste token manually', tr: 'Method 2: Paste token manually', vi: 'Method 2: Paste token manually' },
  'usage.manual_collapse': { zh: '收起手动粘贴', en: 'Collapse manual paste', ja: 'Collapse manual paste', ko: 'Collapse manual paste', ar: 'Collapse manual paste', de: 'Collapse manual paste', es: 'Collapse manual paste', fr: 'Collapse manual paste', hi: 'Collapse manual paste', it: 'Collapse manual paste', nl: 'Collapse manual paste', pl: 'Collapse manual paste', pt: 'Collapse manual paste', ru: 'Collapse manual paste', th: 'Collapse manual paste', tr: 'Collapse manual paste', vi: 'Collapse manual paste' },
  'usage.save_token': { zh: '保存 Token', en: 'Save Token', ja: 'Save Token', ko: 'Save Token', ar: 'Save Token', de: 'Save Token', es: 'Save Token', fr: 'Save Token', hi: 'Save Token', it: 'Save Token', nl: 'Save Token', pl: 'Save Token', pt: 'Save Token', ru: 'Save Token', th: 'Save Token', tr: 'Save Token', vi: 'Save Token' },
  'usage.clear_token': { zh: '清除 Token', en: 'Clear Token', ja: 'Clear Token', ko: 'Clear Token', ar: 'Clear Token', de: 'Clear Token', es: 'Clear Token', fr: 'Clear Token', hi: 'Clear Token', it: 'Clear Token', nl: 'Clear Token', pl: 'Clear Token', pt: 'Clear Token', ru: 'Clear Token', th: 'Clear Token', tr: 'Clear Token', vi: 'Clear Token' },

  // MiMo
  'mimo.login': { zh: 'MiMo 登录', en: 'MiMo Login', ja: 'MiMo Login', ko: 'MiMo Login', ar: 'MiMo Login', de: 'MiMo Login', es: 'MiMo Login', fr: 'MiMo Login', hi: 'MiMo Login', it: 'MiMo Login', nl: 'MiMo Login', pl: 'MiMo Login', pt: 'MiMo Login', ru: 'MiMo Login', th: 'MiMo Login', tr: 'MiMo Login', vi: 'MiMo Login' },
  'mimo.login_desc': { zh: '通过小米账号登录 MiMo 平台，登录成功后即可查看余额和用量数据。', en: 'Login to MiMo with Xiaomi account to view balance and usage.', ja: 'Login to MiMo with Xiaomi account to view balance and usage.', ko: 'Login to MiMo with Xiaomi account to view balance and usage.', ar: 'Login to MiMo with Xiaomi account to view balance and usage.', de: 'Login to MiMo with Xiaomi account to view balance and usage.', es: 'Login to MiMo with Xiaomi account to view balance and usage.', fr: 'Login to MiMo with Xiaomi account to view balance and usage.', hi: 'Login to MiMo with Xiaomi account to view balance and usage.', it: 'Login to MiMo with Xiaomi account to view balance and usage.', nl: 'Login to MiMo with Xiaomi account to view balance and usage.', pl: 'Login to MiMo with Xiaomi account to view balance and usage.', pt: 'Login to MiMo with Xiaomi account to view balance and usage.', ru: 'Login to MiMo with Xiaomi account to view balance and usage.', th: 'Login to MiMo with Xiaomi account to view balance and usage.', tr: 'Login to MiMo with Xiaomi account to view balance and usage.', vi: 'Login to MiMo with Xiaomi account to view balance and usage.' },
  'mimo.login_btn': { zh: '打开 MiMo 登录', en: 'Open MiMo Login', ja: 'Open MiMo Login', ko: 'Open MiMo Login', ar: 'Open MiMo Login', de: 'Open MiMo Login', es: 'Open MiMo Login', fr: 'Open MiMo Login', hi: 'Open MiMo Login', it: 'Open MiMo Login', nl: 'Open MiMo Login', pl: 'Open MiMo Login', pt: 'Open MiMo Login', ru: 'Open MiMo Login', th: 'Open MiMo Login', tr: 'Open MiMo Login', vi: 'Open MiMo Login' },
  'mimo.opening': { zh: '正在打开…', en: 'Opening…', ja: 'Opening…', ko: 'Opening…', ar: 'Opening…', de: 'Opening…', es: 'Opening…', fr: 'Opening…', hi: 'Opening…', it: 'Opening…', nl: 'Opening…', pl: 'Opening…', pt: 'Opening…', ru: 'Opening…', th: 'Opening…', tr: 'Opening…', vi: 'Opening…' },
  'mimo.no_key': { zh: 'MiMo 平台通过小米账号登录认证，无需 API Key。', en: 'MiMo uses Xiaomi account login, no API Key needed.', ja: 'MiMo uses Xiaomi account login, no API Key needed.', ko: 'MiMo uses Xiaomi account login, no API Key needed.', ar: 'MiMo uses Xiaomi account login, no API Key needed.', de: 'MiMo uses Xiaomi account login, no API Key needed.', es: 'MiMo uses Xiaomi account login, no API Key needed.', fr: 'MiMo uses Xiaomi account login, no API Key needed.', hi: 'MiMo uses Xiaomi account login, no API Key needed.', it: 'MiMo uses Xiaomi account login, no API Key needed.', nl: 'MiMo uses Xiaomi account login, no API Key needed.', pl: 'MiMo uses Xiaomi account login, no API Key needed.', pt: 'MiMo uses Xiaomi account login, no API Key needed.', ru: 'MiMo uses Xiaomi account login, no API Key needed.', th: 'MiMo uses Xiaomi account login, no API Key needed.', tr: 'MiMo uses Xiaomi account login, no API Key needed.', vi: 'MiMo uses Xiaomi account login, no API Key needed.' },
  'mimo.not_logged_in': { zh: 'MiMo 未登录，请在设置中重新登录小米账号', en: 'MiMo not logged in, please re-login in settings', ja: 'MiMo not logged in, please re-login in settings', ko: 'MiMo not logged in, please re-login in settings', ar: 'MiMo not logged in, please re-login in settings', de: 'MiMo not logged in, please re-login in settings', es: 'MiMo not logged in, please re-login in settings', fr: 'MiMo not logged in, please re-login in settings', hi: 'MiMo not logged in, please re-login in settings', it: 'MiMo not logged in, please re-login in settings', nl: 'MiMo not logged in, please re-login in settings', pl: 'MiMo not logged in, please re-login in settings', pt: 'MiMo not logged in, please re-login in settings', ru: 'MiMo not logged in, please re-login in settings', th: 'MiMo not logged in, please re-login in settings', tr: 'MiMo not logged in, please re-login in settings', vi: 'MiMo not logged in, please re-login in settings' },

  // 图表
  'chart.cache_hit': { zh: '缓存命中明细', en: 'Cache Hit Details', ja: 'Cache Hit Details', ko: 'Cache Hit Details', ar: 'Cache Hit Details', de: 'Cache Hit Details', es: 'Cache Hit Details', fr: 'Cache Hit Details', hi: 'Cache Hit Details', it: 'Cache Hit Details', nl: 'Cache Hit Details', pl: 'Cache Hit Details', pt: 'Cache Hit Details', ru: 'Cache Hit Details', th: 'Cache Hit Details', tr: 'Cache Hit Details', vi: 'Cache Hit Details' },
  'chart.hit': { zh: '命中', en: 'Hit', ja: 'Hit', ko: 'Hit', ar: 'Hit', de: 'Hit', es: 'Hit', fr: 'Hit', hi: 'Hit', it: 'Hit', nl: 'Hit', pl: 'Hit', pt: 'Hit', ru: 'Hit', th: 'Hit', tr: 'Hit', vi: 'Hit' },
  'chart.miss': { zh: '未命中', en: 'Miss', ja: 'Miss', ko: 'Miss', ar: 'Miss', de: 'Miss', es: 'Miss', fr: 'Miss', hi: 'Miss', it: 'Miss', nl: 'Miss', pl: 'Miss', pt: 'Miss', ru: 'Miss', th: 'Miss', tr: 'Miss', vi: 'Miss' },
  'chart.output': { zh: '输出', en: 'Output', ja: 'Output', ko: 'Output', ar: 'Output', de: 'Output', es: 'Output', fr: 'Output', hi: 'Output', it: 'Output', nl: 'Output', pl: 'Output', pt: 'Output', ru: 'Output', th: 'Output', tr: 'Output', vi: 'Output' },
  'chart.hit_rate': { zh: '命中率', en: 'Hit Rate', ja: 'Hit Rate', ko: 'Hit Rate', ar: 'Hit Rate', de: 'Hit Rate', es: 'Hit Rate', fr: 'Hit Rate', hi: 'Hit Rate', it: 'Hit Rate', nl: 'Hit Rate', pl: 'Hit Rate', pt: 'Hit Rate', ru: 'Hit Rate', th: 'Hit Rate', tr: 'Hit Rate', vi: 'Hit Rate' },
  'chart.total': { zh: '合计', en: 'Total', ja: 'Total', ko: 'Total', ar: 'Total', de: 'Total', es: 'Total', fr: 'Total', hi: 'Total', it: 'Total', nl: 'Total', pl: 'Total', pt: 'Total', ru: 'Total', th: 'Total', tr: 'Total', vi: 'Total' },
  'chart.this_week': { zh: '本周', en: 'This week', ja: 'This week', ko: 'This week', ar: 'This week', de: 'This week', es: 'This week', fr: 'This week', hi: 'This week', it: 'This week', nl: 'This week', pl: 'This week', pt: 'This week', ru: 'This week', th: 'This week', tr: 'This week', vi: 'This week' },
  'chart.last_week': { zh: '上周', en: 'Last week', ja: 'Last week', ko: 'Last week', ar: 'Last week', de: 'Last week', es: 'Last week', fr: 'Last week', hi: 'Last week', it: 'Last week', nl: 'Last week', pl: 'Last week', pt: 'Last week', ru: 'Last week', th: 'Last week', tr: 'Last week', vi: 'Last week' },
  'chart.weeks_ago': { zh: '周前', en: 'weeks ago', ja: 'weeks ago', ko: 'weeks ago', ar: 'weeks ago', de: 'weeks ago', es: 'weeks ago', fr: 'weeks ago', hi: 'weeks ago', it: 'weeks ago', nl: 'weeks ago', pl: 'weeks ago', pt: 'weeks ago', ru: 'weeks ago', th: 'weeks ago', tr: 'weeks ago', vi: 'weeks ago' },
  'chart.input_hit': { zh: '输入（命中缓存）', en: 'Input (cache hit)', ja: 'Input (cache hit)', ko: 'Input (cache hit)', ar: 'Input (cache hit)', de: 'Input (cache hit)', es: 'Input (cache hit)', fr: 'Input (cache hit)', hi: 'Input (cache hit)', it: 'Input (cache hit)', nl: 'Input (cache hit)', pl: 'Input (cache hit)', pt: 'Input (cache hit)', ru: 'Input (cache hit)', th: 'Input (cache hit)', tr: 'Input (cache hit)', vi: 'Input (cache hit)' },
  'chart.input_miss': { zh: '输入（未命中缓存）', en: 'Input (cache miss)', ja: 'Input (cache miss)', ko: 'Input (cache miss)', ar: 'Input (cache miss)', de: 'Input (cache miss)', es: 'Input (cache miss)', fr: 'Input (cache miss)', hi: 'Input (cache miss)', it: 'Input (cache miss)', nl: 'Input (cache miss)', pl: 'Input (cache miss)', pt: 'Input (cache miss)', ru: 'Input (cache miss)', th: 'Input (cache miss)', tr: 'Input (cache miss)', vi: 'Input (cache miss)' },

  // 模型详情
  'detail.requests': { zh: 'API 请求次数', en: 'API Requests', ja: 'API Requests', ko: 'API Requests', ar: 'API Requests', de: 'API Requests', es: 'API Requests', fr: 'API Requests', hi: 'API Requests', it: 'API Requests', nl: 'API Requests', pl: 'API Requests', pt: 'API Requests', ru: 'API Requests', th: 'API Requests', tr: 'API Requests', vi: 'API Requests' },
  'detail.daily': { zh: '按日 Token 消耗', en: 'Daily Token Usage', ja: 'Daily Token Usage', ko: 'Daily Token Usage', ar: 'Daily Token Usage', de: 'Daily Token Usage', es: 'Daily Token Usage', fr: 'Daily Token Usage', hi: 'Daily Token Usage', it: 'Daily Token Usage', nl: 'Daily Token Usage', pl: 'Daily Token Usage', pt: 'Daily Token Usage', ru: 'Daily Token Usage', th: 'Daily Token Usage', tr: 'Daily Token Usage', vi: 'Daily Token Usage' },
  'detail.back': { zh: '返回主面板', en: 'Back to Dashboard', ja: 'Back to Dashboard', ko: 'Back to Dashboard', ar: 'Back to Dashboard', de: 'Back to Dashboard', es: 'Back to Dashboard', fr: 'Back to Dashboard', hi: 'Back to Dashboard', it: 'Back to Dashboard', nl: 'Back to Dashboard', pl: 'Back to Dashboard', pt: 'Back to Dashboard', ru: 'Back to Dashboard', th: 'Back to Dashboard', tr: 'Back to Dashboard', vi: 'Back to Dashboard' },

  // 导航
  'nav.refresh': { zh: '刷新', en: 'Refresh', ja: '更新', ko: '새로고침', ar: 'Refresh', de: 'Refresh', es: 'Refresh', fr: 'Refresh', hi: 'Refresh', it: 'Refresh', nl: 'Refresh', pl: 'Refresh', pt: 'Refresh', ru: 'Refresh', th: 'Refresh', tr: 'Refresh', vi: 'Refresh' },
  'nav.settings': { zh: '设置', en: 'Settings', ja: '設定', ko: '설정', ar: 'Settings', de: 'Settings', es: 'Settings', fr: 'Settings', hi: 'Settings', it: 'Settings', nl: 'Settings', pl: 'Settings', pt: 'Settings', ru: 'Settings', th: 'Settings', tr: 'Settings', vi: 'Settings' },
  'nav.close': { zh: '关闭', en: 'Close', ja: '閉じる', ko: '닫기', ar: 'Close', de: 'Close', es: 'Close', fr: 'Close', hi: 'Close', it: 'Close', nl: 'Close', pl: 'Close', pt: 'Close', ru: 'Close', th: 'Close', tr: 'Close', vi: 'Close' },

  // 语言
  'settings.language': { zh: '语言', en: 'Language', ja: '言語', ko: '언어', ar: 'Language', de: 'Language', es: 'Language', fr: 'Language', hi: 'Language', it: 'Language', nl: 'Language', pl: 'Language', pt: 'Language', ru: 'Language', th: 'Language', tr: 'Language', vi: 'Language' },
  'settings.language_desc': { zh: '选择界面显示语言。', en: 'Choose display language.', ja: '表示言語を選択してください。', ko: '표시 언어를 선택하세요.', ar: 'Choose display language.', de: 'Choose display language.', es: 'Choose display language.', fr: 'Choose display language.', hi: 'Choose display language.', it: 'Choose display language.', nl: 'Choose display language.', pl: 'Choose display language.', pt: 'Choose display language.', ru: 'Choose display language.', th: 'Choose display language.', tr: 'Choose display language.', vi: 'Choose display language.' },
};

let currentLang: Lang = 'zh';

export function setLang(lang: Lang) {
  currentLang = lang;
  try { localStorage.setItem('dsm-lang', lang); } catch {}
}

export function getLang(): Lang {
  return currentLang;
}

export function initLang() {
  try {
    const saved = localStorage.getItem('dsm-lang');
    if (saved === 'en' || saved === 'zh' || saved === 'ja' || saved === 'ko') currentLang = saved as Lang;
  } catch {}
}

export function t(key: string): string {
  const entry = translations[key];
  if (!entry) return key;
  return entry[currentLang] || entry['zh'] || key;
}
