// ─── i18n 国际化支持 ──────────────────────────────────────
// 简单的键值对翻译系统，支持中英文切换

export type Lang = 'zh' | 'en' | 'ar' | 'de' | 'es' | 'fr' | 'hi' | 'it' | 'ja' | 'ko' | 'nl' | 'pl' | 'pt' | 'ru' | 'th' | 'tr' | 'vi';

// 语言列表：zh/en 固定在前，分隔线后 17 种语言全部按原生名称 Unicode 排序（zh/en 重复出现）
export const PINNED_LANGS: Lang[] = ['zh', 'en'];

// 全部 17 种语言按原生名称 Unicode 码点排序
export const LANG_OPTIONS: { code: Lang; label: string }[] = [
  { code: 'ar', label: 'العربية' },
  { code: 'de', label: 'Deutsch' },
  { code: 'en', label: 'English' },
  { code: 'es', label: 'Español' },
  { code: 'fr', label: 'Français' },
  { code: 'hi', label: 'हिन्दी' },
  { code: 'it', label: 'Italiano' },
  { code: 'ja', label: '日本語' },
  { code: 'ko', label: '한국어' },
  { code: 'nl', label: 'Nederlands' },
  { code: 'pl', label: 'Polski' },
  { code: 'pt', label: 'Português' },
  { code: 'ru', label: 'Русский' },
  { code: 'th', label: 'ไทย' },
  { code: 'tr', label: 'Türkçe' },
  { code: 'vi', label: 'Tiếng Việt' },
  { code: 'zh', label: '简体中文' },
];

const translations: Record<string, Record<Lang, string>> = {
  // 通用
  'app.loading': { zh: '查询中…', en: 'Loading…', ja: 'Loading…', ko: 'Loading…', ar: 'Loading…', de: 'Loading…', es: 'Loading…', fr: 'Loading…', hi: 'Loading…', it: 'Loading…', nl: 'Loading…', pl: 'Loading…', pt: 'Loading…', ru: 'Loading…', th: 'Loading…', tr: 'Loading…', vi: 'Loading…' },
  'app.error': { zh: '查询失败', en: 'Query failed', ja: 'Query failed', ko: 'Query failed', ar: 'Query failed', de: 'Query failed', es: 'Query failed', fr: 'Query failed', hi: 'Query failed', it: 'Query failed', nl: 'Query failed', pl: 'Query failed', pt: 'Query failed', ru: 'Query failed', th: 'Query failed', tr: 'Query failed', vi: 'Query failed' },
  'app.unconfigured': { zh: '未配置', en: 'Not configured', ja: 'Not configured', ko: 'Not configured', ar: 'Not configured', de: 'Not configured', es: 'Not configured', fr: 'Not configured', hi: 'Not configured', it: 'Not configured', nl: 'Not configured', pl: 'Not configured', pt: 'Not configured', ru: 'Not configured', th: 'Not configured', tr: 'Not configured', vi: 'Not configured' },
  'app.unconfigured_token': { zh: '未配置 Token', en: 'Token not configured', ja: 'Token not configured', ko: 'Token not configured', ar: 'Token not configured', de: 'Token not configured', es: 'Token not configured', fr: 'Token not configured', hi: 'Token not configured', it: 'Token not configured', nl: 'Token not configured', pl: 'Token not configured', pt: 'Token not configured', ru: 'Token not configured', th: 'Token not configured', tr: 'Token not configured', vi: 'Token not configured' },
  'app.unavailable': { zh: '不可用', en: 'Unavailable', ja: 'Unavailable', ko: 'Unavailable', ar: 'Unavailable', de: 'Unavailable', es: 'Unavailable', fr: 'Unavailable', hi: 'Unavailable', it: 'Unavailable', nl: 'Unavailable', pl: 'Unavailable', pt: 'Unavailable', ru: 'Unavailable', th: 'Unavailable', tr: 'Unavailable', vi: 'Unavailable' },
  'app.no_data': { zh: '暂无数据', en: 'No data', ja: 'No data', ko: 'No data', ar: 'No data', de: 'No data', es: 'No data', fr: 'No data', hi: 'No data', it: 'No data', nl: 'No data', pl: 'No data', pt: 'No data', ru: 'No data', th: 'No data', tr: 'No data', vi: 'No data' },
  'app.tokens': { zh: 'tokens', en: 'tokens', ja: 'tokens', ko: 'tokens', ar: 'tokens', de: 'tokens', es: 'tokens', fr: 'tokens', hi: 'tokens', it: 'tokens', nl: 'tokens', pl: 'tokens', pt: 'tokens', ru: 'tokens', th: 'tokens', tr: 'tokens', vi: 'tokens' },

  // 余额
  'balance.title': { zh: '账户余额', en: 'Account Balance', ja: 'Account Balance', ko: 'Account Balance', ar: 'Account Balance', de: 'Account Balance', es: 'Account Balance', fr: 'Account Balance', hi: 'Account Balance', it: 'Account Balance', nl: 'Account Balance', pl: 'Account Balance', pt: 'Account Balance', ru: 'Account Balance', th: 'Account Balance', tr: 'Account Balance', vi: 'Account Balance' },
  'balance.available': { zh: '可用', en: 'Available', ja: 'Available', ko: 'Available', ar: 'Available', de: 'Available', es: 'Available', fr: 'Available', hi: 'Available', it: 'Available', nl: 'Available', pl: 'Available', pt: 'Available', ru: 'Available', th: 'Available', tr: 'Available', vi: 'Available' },
  'balance.insufficient': { zh: '余额不足', en: 'Insufficient', ja: 'Insufficient', ko: 'Insufficient', ar: 'Insufficient', de: 'Insufficient', es: 'Insufficient', fr: 'Insufficient', hi: 'Insufficient', it: 'Insufficient', nl: 'Insufficient', pl: 'Insufficient', pt: 'Insufficient', ru: 'Insufficient', th: 'Insufficient', tr: 'Insufficient', vi: 'Insufficient' },
  'balance.today': { zh: '当日消耗', en: 'Today', ja: 'Today', ko: 'Today', ar: 'Today', de: 'Today', es: 'Today', fr: 'Today', hi: 'Today', it: 'Today', nl: 'Today', pl: 'Today', pt: 'Today', ru: 'Today', th: 'Today', tr: 'Today', vi: 'Today' },
  'balance.monthly': { zh: '本月消费', en: 'This Month', ja: 'This Month', ko: 'This Month', ar: 'This Month', de: 'This Month', es: 'This Month', fr: 'This Month', hi: 'This Month', it: 'This Month', nl: 'This Month', pl: 'This Month', pt: 'This Month', ru: 'This Month', th: 'This Month', tr: 'This Month', vi: 'This Month' },

  // 设置
  'settings.title': { zh: '设置', en: 'Settings', ja: 'Settings', ko: 'Settings', ar: 'Settings', de: 'Settings', es: 'Settings', fr: 'Settings', hi: 'Settings', it: 'Settings', nl: 'Settings', pl: 'Settings', pt: 'Settings', ru: 'Settings', th: 'Settings', tr: 'Settings', vi: 'Settings' },
  'settings.api_key': { zh: 'API Key', en: 'API Key', ja: 'API Key', ko: 'API Key', ar: 'API Key', de: 'API Key', es: 'API Key', fr: 'API Key', hi: 'API Key', it: 'API Key', nl: 'API Key', pl: 'API Key', pt: 'API Key', ru: 'API Key', th: 'API Key', tr: 'API Key', vi: 'API Key' },
  'settings.api_key_desc': { zh: '用于调用 API 获取余额和用量数据。', en: 'Used to call API for balance and usage data.', ja: 'Used to call API for balance and usage data.', ko: 'Used to call API for balance and usage data.', ar: 'Used to call API for balance and usage data.', de: 'Used to call API for balance and usage data.', es: 'Used to call API for balance and usage data.', fr: 'Used to call API for balance and usage data.', hi: 'Used to call API for balance and usage data.', it: 'Used to call API for balance and usage data.', nl: 'Used to call API for balance and usage data.', pl: 'Used to call API for balance and usage data.', pt: 'Used to call API for balance and usage data.', ru: 'Used to call API for balance and usage data.', th: 'Used to call API for balance and usage data.', tr: 'Used to call API for balance and usage data.', vi: 'Used to call API for balance and usage data.' },
  'settings.save': { zh: '验证并保存', en: 'Verify & Save', ja: 'Verify & Save', ko: 'Verify & Save', ar: 'Verify & Save', de: 'Verify & Save', es: 'Verify & Save', fr: 'Verify & Save', hi: 'Verify & Save', it: 'Verify & Save', nl: 'Verify & Save', pl: 'Verify & Save', pt: 'Verify & Save', ru: 'Verify & Save', th: 'Verify & Save', tr: 'Verify & Save', vi: 'Verify & Save' },
  'settings.clear': { zh: '清除 Key', en: 'Clear Key', ja: 'Clear Key', ko: 'Clear Key', ar: 'Clear Key', de: 'Clear Key', es: 'Clear Key', fr: 'Clear Key', hi: 'Clear Key', it: 'Clear Key', nl: 'Clear Key', pl: 'Clear Key', pt: 'Clear Key', ru: 'Clear Key', th: 'Clear Key', tr: 'Clear Key', vi: 'Clear Key' },
  'settings.verified': { zh: '已配置', en: 'Configured', ja: 'Configured', ko: 'Configured', ar: 'Configured', de: 'Configured', es: 'Configured', fr: 'Configured', hi: 'Configured', it: 'Configured', nl: 'Configured', pl: 'Configured', pt: 'Configured', ru: 'Configured', th: 'Configured', tr: 'Configured', vi: 'Configured' },
  'settings.not_configured': { zh: '未配置', en: 'Not configured', ja: 'Not configured', ko: 'Not configured', ar: 'Not configured', de: 'Not configured', es: 'Not configured', fr: 'Not configured', hi: 'Not configured', it: 'Not configured', nl: 'Not configured', pl: 'Not configured', pt: 'Not configured', ru: 'Not configured', th: 'Not configured', tr: 'Not configured', vi: 'Not configured' },
  'settings.general': { zh: '通用', en: 'General', ja: 'General', ko: 'General', ar: 'General', de: 'General', es: 'General', fr: 'General', hi: 'General', it: 'General', nl: 'General', pl: 'General', pt: 'General', ru: 'General', th: 'General', tr: 'General', vi: 'General' },
  'settings.autostart': { zh: '开机自启', en: 'Auto Start', ja: 'Auto Start', ko: 'Auto Start', ar: 'Auto Start', de: 'Auto Start', es: 'Auto Start', fr: 'Auto Start', hi: 'Auto Start', it: 'Auto Start', nl: 'Auto Start', pl: 'Auto Start', pt: 'Auto Start', ru: 'Auto Start', th: 'Auto Start', tr: 'Auto Start', vi: 'Auto Start' },
  'settings.autostart_desc': { zh: '开启后，每次登录 Windows 时自动启动应用。', en: 'Auto start on Windows login.', ja: 'Auto start on Windows login.', ko: 'Auto start on Windows login.', ar: 'Auto start on Windows login.', de: 'Auto start on Windows login.', es: 'Auto start on Windows login.', fr: 'Auto start on Windows login.', hi: 'Auto start on Windows login.', it: 'Auto start on Windows login.', nl: 'Auto start on Windows login.', pl: 'Auto start on Windows login.', pt: 'Auto start on Windows login.', ru: 'Auto start on Windows login.', th: 'Auto start on Windows login.', tr: 'Auto start on Windows login.', vi: 'Auto start on Windows login.' },
  'settings.auto_refresh': { zh: '自动刷新', en: 'Auto Refresh', ja: 'Auto Refresh', ko: 'Auto Refresh', ar: 'Auto Refresh', de: 'Auto Refresh', es: 'Auto Refresh', fr: 'Auto Refresh', hi: 'Auto Refresh', it: 'Auto Refresh', nl: 'Auto Refresh', pl: 'Auto Refresh', pt: 'Auto Refresh', ru: 'Auto Refresh', th: 'Auto Refresh', tr: 'Auto Refresh', vi: 'Auto Refresh' },
  'settings.auto_refresh_desc': { zh: '开启后，按设定周期自动拉取最新数据。', en: 'Automatically fetch latest data at set intervals.', ja: 'Automatically fetch latest data at set intervals.', ko: 'Automatically fetch latest data at set intervals.', ar: 'Automatically fetch latest data at set intervals.', de: 'Automatically fetch latest data at set intervals.', es: 'Automatically fetch latest data at set intervals.', fr: 'Automatically fetch latest data at set intervals.', hi: 'Automatically fetch latest data at set intervals.', it: 'Automatically fetch latest data at set intervals.', nl: 'Automatically fetch latest data at set intervals.', pl: 'Automatically fetch latest data at set intervals.', pt: 'Automatically fetch latest data at set intervals.', ru: 'Automatically fetch latest data at set intervals.', th: 'Automatically fetch latest data at set intervals.', tr: 'Automatically fetch latest data at set intervals.', vi: 'Automatically fetch latest data at set intervals.' },
  'settings.window_size': { zh: '窗口大小', en: 'Window Size', ja: 'Window Size', ko: 'Window Size', ar: 'Window Size', de: 'Window Size', es: 'Window Size', fr: 'Window Size', hi: 'Window Size', it: 'Window Size', nl: 'Window Size', pl: 'Window Size', pt: 'Window Size', ru: 'Window Size', th: 'Window Size', tr: 'Window Size', vi: 'Window Size' },
  'settings.window_desc': { zh: '选择预设窗口尺寸，或拖拽窗口边缘自由调整。', en: 'Choose a preset size or drag window edges.', ja: 'Choose a preset size or drag window edges.', ko: 'Choose a preset size or drag window edges.', ar: 'Choose a preset size or drag window edges.', de: 'Choose a preset size or drag window edges.', es: 'Choose a preset size or drag window edges.', fr: 'Choose a preset size or drag window edges.', hi: 'Choose a preset size or drag window edges.', it: 'Choose a preset size or drag window edges.', nl: 'Choose a preset size or drag window edges.', pl: 'Choose a preset size or drag window edges.', pt: 'Choose a preset size or drag window edges.', ru: 'Choose a preset size or drag window edges.', th: 'Choose a preset size or drag window edges.', tr: 'Choose a preset size or drag window edges.', vi: 'Choose a preset size or drag window edges.' },
  'settings.compact': { zh: '紧凑', en: 'Compact', ja: 'Compact', ko: 'Compact', ar: 'Compact', de: 'Compact', es: 'Compact', fr: 'Compact', hi: 'Compact', it: 'Compact', nl: 'Compact', pl: 'Compact', pt: 'Compact', ru: 'Compact', th: 'Compact', tr: 'Compact', vi: 'Compact' },
  'settings.standard': { zh: '标准', en: 'Standard', ja: 'Standard', ko: 'Standard', ar: 'Standard', de: 'Standard', es: 'Standard', fr: 'Standard', hi: 'Standard', it: 'Standard', nl: 'Standard', pl: 'Standard', pt: 'Standard', ru: 'Standard', th: 'Standard', tr: 'Standard', vi: 'Standard' },
  'settings.wide': { zh: '宽屏', en: 'Wide', ja: 'Wide', ko: 'Wide', ar: 'Wide', de: 'Wide', es: 'Wide', fr: 'Wide', hi: 'Wide', it: 'Wide', nl: 'Wide', pl: 'Wide', pt: 'Wide', ru: 'Wide', th: 'Wide', tr: 'Wide', vi: 'Wide' },
  'settings.large': { zh: '大屏', en: 'Large', ja: 'Large', ko: 'Large', ar: 'Large', de: 'Large', es: 'Large', fr: 'Large', hi: 'Large', it: 'Large', nl: 'Large', pl: 'Large', pt: 'Large', ru: 'Large', th: 'Large', tr: 'Large', vi: 'Large' },
  'settings.about': { zh: '关于', en: 'About', ja: 'About', ko: 'About', ar: 'About', de: 'About', es: 'About', fr: 'About', hi: 'About', it: 'About', nl: 'About', pl: 'About', pt: 'About', ru: 'About', th: 'About', tr: 'About', vi: 'About' },
  'settings.version': { zh: '当前版本', en: 'Version', ja: 'Version', ko: 'Version', ar: 'Version', de: 'Version', es: 'Version', fr: 'Version', hi: 'Version', it: 'Version', nl: 'Version', pl: 'Version', pt: 'Version', ru: 'Version', th: 'Version', tr: 'Version', vi: 'Version' },
  'settings.check_update': { zh: '检查更新', en: 'Check for Updates', ja: 'Check for Updates', ko: 'Check for Updates', ar: 'Check for Updates', de: 'Check for Updates', es: 'Check for Updates', fr: 'Check for Updates', hi: 'Check for Updates', it: 'Check for Updates', nl: 'Check for Updates', pl: 'Check for Updates', pt: 'Check for Updates', ru: 'Check for Updates', th: 'Check for Updates', tr: 'Check for Updates', vi: 'Check for Updates' },
  'settings.checking': { zh: '检查中…', en: 'Checking…', ja: 'Checking…', ko: 'Checking…', ar: 'Checking…', de: 'Checking…', es: 'Checking…', fr: 'Checking…', hi: 'Checking…', it: 'Checking…', nl: 'Checking…', pl: 'Checking…', pt: 'Checking…', ru: 'Checking…', th: 'Checking…', tr: 'Checking…', vi: 'Checking…' },
  'settings.latest': { zh: '已是最新版本', en: 'Up to date', ja: 'Up to date', ko: 'Up to date', ar: 'Up to date', de: 'Up to date', es: 'Up to date', fr: 'Up to date', hi: 'Up to date', it: 'Up to date', nl: 'Up to date', pl: 'Up to date', pt: 'Up to date', ru: 'Up to date', th: 'Up to date', tr: 'Up to date', vi: 'Up to date' },
  'settings.update_found': { zh: '发现新版本', en: 'Update available', ja: 'Update available', ko: 'Update available', ar: 'Update available', de: 'Update available', es: 'Update available', fr: 'Update available', hi: 'Update available', it: 'Update available', nl: 'Update available', pl: 'Update available', pt: 'Update available', ru: 'Update available', th: 'Update available', tr: 'Update available', vi: 'Update available' },
  'settings.download': { zh: '请前往 GitHub Releases 下载最新安装包。', en: 'Please download from GitHub Releases.', ja: 'Please download from GitHub Releases.', ko: 'Please download from GitHub Releases.', ar: 'Please download from GitHub Releases.', de: 'Please download from GitHub Releases.', es: 'Please download from GitHub Releases.', fr: 'Please download from GitHub Releases.', hi: 'Please download from GitHub Releases.', it: 'Please download from GitHub Releases.', nl: 'Please download from GitHub Releases.', pl: 'Please download from GitHub Releases.', pt: 'Please download from GitHub Releases.', ru: 'Please download from GitHub Releases.', th: 'Please download from GitHub Releases.', tr: 'Please download from GitHub Releases.', vi: 'Please download from GitHub Releases.' },

  // 余额提醒
  'notify.title': { zh: '余额提醒', en: 'Balance Alert', ja: 'Balance Alert', ko: 'Balance Alert', ar: 'Balance Alert', de: 'Balance Alert', es: 'Balance Alert', fr: 'Balance Alert', hi: 'Balance Alert', it: 'Balance Alert', nl: 'Balance Alert', pl: 'Balance Alert', pt: 'Balance Alert', ru: 'Balance Alert', th: 'Balance Alert', tr: 'Balance Alert', vi: 'Balance Alert' },
  'notify.toggle': { zh: '低余额通知', en: 'Low Balance Alert', ja: 'Low Balance Alert', ko: 'Low Balance Alert', ar: 'Low Balance Alert', de: 'Low Balance Alert', es: 'Low Balance Alert', fr: 'Low Balance Alert', hi: 'Low Balance Alert', it: 'Low Balance Alert', nl: 'Low Balance Alert', pl: 'Low Balance Alert', pt: 'Low Balance Alert', ru: 'Low Balance Alert', th: 'Low Balance Alert', tr: 'Low Balance Alert', vi: 'Low Balance Alert' },
  'notify.desc': { zh: '当账户余额低于设定阈值时，弹出 Windows 通知提醒。默认关闭。', en: 'Show Windows notification when balance is below threshold. Off by default.', ja: 'Show Windows notification when balance is below threshold. Off by default.', ko: 'Show Windows notification when balance is below threshold. Off by default.', ar: 'Show Windows notification when balance is below threshold. Off by default.', de: 'Show Windows notification when balance is below threshold. Off by default.', es: 'Show Windows notification when balance is below threshold. Off by default.', fr: 'Show Windows notification when balance is below threshold. Off by default.', hi: 'Show Windows notification when balance is below threshold. Off by default.', it: 'Show Windows notification when balance is below threshold. Off by default.', nl: 'Show Windows notification when balance is below threshold. Off by default.', pl: 'Show Windows notification when balance is below threshold. Off by default.', pt: 'Show Windows notification when balance is below threshold. Off by default.', ru: 'Show Windows notification when balance is below threshold. Off by default.', th: 'Show Windows notification when balance is below threshold. Off by default.', tr: 'Show Windows notification when balance is below threshold. Off by default.', vi: 'Show Windows notification when balance is below threshold. Off by default.' },
  'notify.threshold': { zh: '阈值', en: 'Threshold', ja: 'Threshold', ko: 'Threshold', ar: 'Threshold', de: 'Threshold', es: 'Threshold', fr: 'Threshold', hi: 'Threshold', it: 'Threshold', nl: 'Threshold', pl: 'Threshold', pt: 'Threshold', ru: 'Threshold', th: 'Threshold', tr: 'Threshold', vi: 'Threshold' },

  // DeepSeek 用量同步
  'usage.title': { zh: '用量同步 Token', en: 'Usage Sync Token', ja: 'Usage Sync Token', ko: 'Usage Sync Token', ar: 'Usage Sync Token', de: 'Usage Sync Token', es: 'Usage Sync Token', fr: 'Usage Sync Token', hi: 'Usage Sync Token', it: 'Usage Sync Token', nl: 'Usage Sync Token', pl: 'Usage Sync Token', pt: 'Usage Sync Token', ru: 'Usage Sync Token', th: 'Usage Sync Token', tr: 'Usage Sync Token', vi: 'Usage Sync Token' },
  'usage.desc': { zh: '用于同步 Token 用量、消费和趋势图。需网页登录 token。', en: 'Sync token usage and trends. Requires web login token.', ja: 'Sync token usage and trends. Requires web login token.', ko: 'Sync token usage and trends. Requires web login token.', ar: 'Sync token usage and trends. Requires web login token.', de: 'Sync token usage and trends. Requires web login token.', es: 'Sync token usage and trends. Requires web login token.', fr: 'Sync token usage and trends. Requires web login token.', hi: 'Sync token usage and trends. Requires web login token.', it: 'Sync token usage and trends. Requires web login token.', nl: 'Sync token usage and trends. Requires web login token.', pl: 'Sync token usage and trends. Requires web login token.', pt: 'Sync token usage and trends. Requires web login token.', ru: 'Sync token usage and trends. Requires web login token.', th: 'Sync token usage and trends. Requires web login token.', tr: 'Sync token usage and trends. Requires web login token.', vi: 'Sync token usage and trends. Requires web login token.' },
  'usage.auto_sync': { zh: '网页登录自动同步', en: 'Web Login Auto Sync', ja: 'Web Login Auto Sync', ko: 'Web Login Auto Sync', ar: 'Web Login Auto Sync', de: 'Web Login Auto Sync', es: 'Web Login Auto Sync', fr: 'Web Login Auto Sync', hi: 'Web Login Auto Sync', it: 'Web Login Auto Sync', nl: 'Web Login Auto Sync', pl: 'Web Login Auto Sync', pt: 'Web Login Auto Sync', ru: 'Web Login Auto Sync', th: 'Web Login Auto Sync', tr: 'Web Login Auto Sync', vi: 'Web Login Auto Sync' },
  'usage.waiting': { zh: '等待登录', en: 'Waiting for login', ja: 'Waiting for login', ko: 'Waiting for login', ar: 'Waiting for login', de: 'Waiting for login', es: 'Waiting for login', fr: 'Waiting for login', hi: 'Waiting for login', it: 'Waiting for login', nl: 'Waiting for login', pl: 'Waiting for login', pt: 'Waiting for login', ru: 'Waiting for login', th: 'Waiting for login', tr: 'Waiting for login', vi: 'Waiting for login' },
  'usage.manual': { zh: '方式二：手动粘贴 token', en: 'Method 2: Paste token manually', ja: 'Method 2: Paste token manually', ko: 'Method 2: Paste token manually', ar: 'Method 2: Paste token manually', de: 'Method 2: Paste token manually', es: 'Method 2: Paste token manually', fr: 'Method 2: Paste token manually', hi: 'Method 2: Paste token manually', it: 'Method 2: Paste token manually', nl: 'Method 2: Paste token manually', pl: 'Method 2: Paste token manually', pt: 'Method 2: Paste token manually', ru: 'Method 2: Paste token manually', th: 'Method 2: Paste token manually', tr: 'Method 2: Paste token manually', vi: 'Method 2: Paste token manually' },
  'usage.manual_collapse': { zh: '收起手动粘贴', en: 'Collapse manual paste', ja: 'Collapse manual paste', ko: 'Collapse manual paste', ar: 'Collapse manual paste', de: 'Collapse manual paste', es: 'Collapse manual paste', fr: 'Collapse manual paste', hi: 'Collapse manual paste', it: 'Collapse manual paste', nl: 'Collapse manual paste', pl: 'Collapse manual paste', pt: 'Collapse manual paste', ru: 'Collapse manual paste', th: 'Collapse manual paste', tr: 'Collapse manual paste', vi: 'Collapse manual paste' },
  'usage.save_token': { zh: '保存 Token', en: 'Save Token', ja: 'Save Token', ko: 'Save Token', ar: 'Save Token', de: 'Save Token', es: 'Save Token', fr: 'Save Token', hi: 'Save Token', it: 'Save Token', nl: 'Save Token', pl: 'Save Token', pt: 'Save Token', ru: 'Save Token', th: 'Save Token', tr: 'Save Token', vi: 'Save Token' },
  'usage.clear_token': { zh: '清除 Token', en: 'Clear Token', ja: 'Clear Token', ko: 'Clear Token', ar: 'Clear Token', de: 'Clear Token', es: 'Clear Token', fr: 'Clear Token', hi: 'Clear Token', it: 'Clear Token', nl: 'Clear Token', pl: 'Clear Token', pt: 'Clear Token', ru: 'Clear Token', th: 'Clear Token', tr: 'Clear Token', vi: 'Clear Token' },

  // MiMo
  'mimo.login': { zh: 'MiMo 登录', en: 'MiMo Login', ja: 'MiMo Login', ko: 'MiMo Login', ar: 'MiMo Login', de: 'MiMo Login', es: 'MiMo Login', fr: 'MiMo Login', hi: 'MiMo Login', it: 'MiMo Login', nl: 'MiMo Login', pl: 'MiMo Login', pt: 'MiMo Login', ru: 'MiMo Login', th: 'MiMo Login', tr: 'MiMo Login', vi: 'MiMo Login' },
  'mimo.login_desc': { zh: '通过小米账号登录 MiMo 平台，登录成功后即可查看余额和用量数据。', en: 'Login to MiMo with Xiaomi account to view balance and usage.', ja: 'Login to MiMo with Xiaomi account to view balance and usage.', ko: 'Login to MiMo with Xiaomi account to view balance and usage.', ar: 'Login to MiMo with Xiaomi account to view balance and usage.', de: 'Login to MiMo with Xiaomi account to view balance and usage.', es: 'Login to MiMo with Xiaomi account to view balance and usage.', fr: 'Login to MiMo with Xiaomi account to view balance and usage.', hi: 'Login to MiMo with Xiaomi account to view balance and usage.', it: 'Login to MiMo with Xiaomi account to view balance and usage.', nl: 'Login to MiMo with Xiaomi account to view balance and usage.', pl: 'Login to MiMo with Xiaomi account to view balance and usage.', pt: 'Login to MiMo with Xiaomi account to view balance and usage.', ru: 'Login to MiMo with Xiaomi account to view balance and usage.', th: 'Login to MiMo with Xiaomi account to view balance and usage.', tr: 'Login to MiMo with Xiaomi account to view balance and usage.', vi: 'Login to MiMo with Xiaomi account to view balance and usage.' },
  'mimo.login_btn': { zh: '打开 MiMo 登录', en: 'Open MiMo Login', ja: 'Open MiMo Login', ko: 'Open MiMo Login', ar: 'Open MiMo Login', de: 'Open MiMo Login', es: 'Open MiMo Login', fr: 'Open MiMo Login', hi: 'Open MiMo Login', it: 'Open MiMo Login', nl: 'Open MiMo Login', pl: 'Open MiMo Login', pt: 'Open MiMo Login', ru: 'Open MiMo Login', th: 'Open MiMo Login', tr: 'Open MiMo Login', vi: 'Open MiMo Login' },
  'mimo.opening': { zh: '正在打开…', en: 'Opening…', ja: 'Opening…', ko: 'Opening…', ar: 'Opening…', de: 'Opening…', es: 'Opening…', fr: 'Opening…', hi: 'Opening…', it: 'Opening…', nl: 'Opening…', pl: 'Opening…', pt: 'Opening…', ru: 'Opening…', th: 'Opening…', tr: 'Opening…', vi: 'Opening…' },
  'mimo.no_key': { zh: 'MiMo 平台通过小米账号登录认证，无需 API Key。', en: 'MiMo uses Xiaomi account login, no API Key needed.', ja: 'MiMo uses Xiaomi account login, no API Key needed.', ko: 'MiMo uses Xiaomi account login, no API Key needed.', ar: 'MiMo uses Xiaomi account login, no API Key needed.', de: 'MiMo uses Xiaomi account login, no API Key needed.', es: 'MiMo uses Xiaomi account login, no API Key needed.', fr: 'MiMo uses Xiaomi account login, no API Key needed.', hi: 'MiMo uses Xiaomi account login, no API Key needed.', it: 'MiMo uses Xiaomi account login, no API Key needed.', nl: 'MiMo uses Xiaomi account login, no API Key needed.', pl: 'MiMo uses Xiaomi account login, no API Key needed.', pt: 'MiMo uses Xiaomi account login, no API Key needed.', ru: 'MiMo uses Xiaomi account login, no API Key needed.', th: 'MiMo uses Xiaomi account login, no API Key needed.', tr: 'MiMo uses Xiaomi account login, no API Key needed.', vi: 'MiMo uses Xiaomi account login, no API Key needed.' },
  'mimo.not_logged_in': { zh: 'MiMo 未登录，请在设置中重新登录小米账号', en: 'MiMo not logged in, please re-login in settings', ja: 'MiMo not logged in, please re-login in settings', ko: 'MiMo not logged in, please re-login in settings', ar: 'MiMo not logged in, please re-login in settings', de: 'MiMo not logged in, please re-login in settings', es: 'MiMo not logged in, please re-login in settings', fr: 'MiMo not logged in, please re-login in settings', hi: 'MiMo not logged in, please re-login in settings', it: 'MiMo not logged in, please re-login in settings', nl: 'MiMo not logged in, please re-login in settings', pl: 'MiMo not logged in, please re-login in settings', pt: 'MiMo not logged in, please re-login in settings', ru: 'MiMo not logged in, please re-login in settings', th: 'MiMo not logged in, please re-login in settings', tr: 'MiMo not logged in, please re-login in settings', vi: 'MiMo not logged in, please re-login in settings' },

  // 图表
  'chart.cache_hit': { zh: '缓存命中明细', en: 'Cache Hit Details', ja: 'Cache Hit Details', ko: 'Cache Hit Details', ar: 'Cache Hit Details', de: 'Cache Hit Details', es: 'Cache Hit Details', fr: 'Cache Hit Details', hi: 'Cache Hit Details', it: 'Cache Hit Details', nl: 'Cache Hit Details', pl: 'Cache Hit Details', pt: 'Cache Hit Details', ru: 'Cache Hit Details', th: 'Cache Hit Details', tr: 'Cache Hit Details', vi: 'Cache Hit Details' },
  'chart.hit': { zh: '命中', en: 'Hit', ja: 'Hit', ko: 'Hit', ar: 'Hit', de: 'Hit', es: 'Hit', fr: 'Hit', hi: 'Hit', it: 'Hit', nl: 'Hit', pl: 'Hit', pt: 'Hit', ru: 'Hit', th: 'Hit', tr: 'Hit', vi: 'Hit' },
  'chart.miss': { zh: '未命中', en: 'Miss', ja: 'Miss', ko: 'Miss', ar: 'Miss', de: 'Miss', es: 'Miss', fr: 'Miss', hi: 'Miss', it: 'Miss', nl: 'Miss', pl: 'Miss', pt: 'Miss', ru: 'Miss', th: 'Miss', tr: 'Miss', vi: 'Miss' },
  'chart.output': { zh: '输出', en: 'Output', ja: 'Output', ko: 'Output', ar: 'Output', de: 'Output', es: 'Output', fr: 'Output', hi: 'Output', it: 'Output', nl: 'Output', pl: 'Output', pt: 'Output', ru: 'Output', th: 'Output', tr: 'Output', vi: 'Output' },
  'chart.hit_rate': { zh: '命中率', en: 'Hit Rate', ja: 'Hit Rate', ko: 'Hit Rate', ar: 'Hit Rate', de: 'Hit Rate', es: 'Hit Rate', fr: 'Hit Rate', hi: 'Hit Rate', it: 'Hit Rate', nl: 'Hit Rate', pl: 'Hit Rate', pt: 'Hit Rate', ru: 'Hit Rate', th: 'Hit Rate', tr: 'Hit Rate', vi: 'Hit Rate' },
  'chart.total': { zh: '合计', en: 'Total', ja: 'Total', ko: 'Total', ar: 'Total', de: 'Total', es: 'Total', fr: 'Total', hi: 'Total', it: 'Total', nl: 'Total', pl: 'Total', pt: 'Total', ru: 'Total', th: 'Total', tr: 'Total', vi: 'Total' },
  'chart.this_week': { zh: '本周', en: 'This week', ja: 'This week', ko: 'This week', ar: 'This week', de: 'This week', es: 'This week', fr: 'This week', hi: 'This week', it: 'This week', nl: 'This week', pl: 'This week', pt: 'This week', ru: 'This week', th: 'This week', tr: 'This week', vi: 'This week' },
  'chart.last_week': { zh: '上周', en: 'Last week', ja: 'Last week', ko: 'Last week', ar: 'Last week', de: 'Last week', es: 'Last week', fr: 'Last week', hi: 'Last week', it: 'Last week', nl: 'Last week', pl: 'Last week', pt: 'Last week', ru: 'Last week', th: 'Last week', tr: 'Last week', vi: 'Last week' },
  'chart.weeks_ago': { zh: '周前', en: 'weeks ago', ja: 'weeks ago', ko: 'weeks ago', ar: 'weeks ago', de: 'weeks ago', es: 'weeks ago', fr: 'weeks ago', hi: 'weeks ago', it: 'weeks ago', nl: 'weeks ago', pl: 'weeks ago', pt: 'weeks ago', ru: 'weeks ago', th: 'weeks ago', tr: 'weeks ago', vi: 'weeks ago' },
  'chart.input_hit': { zh: '输入（命中缓存）', en: 'Input (cache hit)', ja: 'Input (cache hit)', ko: 'Input (cache hit)', ar: 'Input (cache hit)', de: 'Input (cache hit)', es: 'Input (cache hit)', fr: 'Input (cache hit)', hi: 'Input (cache hit)', it: 'Input (cache hit)', nl: 'Input (cache hit)', pl: 'Input (cache hit)', pt: 'Input (cache hit)', ru: 'Input (cache hit)', th: 'Input (cache hit)', tr: 'Input (cache hit)', vi: 'Input (cache hit)' },
  'chart.input_miss': { zh: '输入（未命中缓存）', en: 'Input (cache miss)', ja: 'Input (cache miss)', ko: 'Input (cache miss)', ar: 'Input (cache miss)', de: 'Input (cache miss)', es: 'Input (cache miss)', fr: 'Input (cache miss)', hi: 'Input (cache miss)', it: 'Input (cache miss)', nl: 'Input (cache miss)', pl: 'Input (cache miss)', pt: 'Input (cache miss)', ru: 'Input (cache miss)', th: 'Input (cache miss)', tr: 'Input (cache miss)', vi: 'Input (cache miss)' },

  // 模型详情
  'detail.requests': { zh: 'API 请求次数', en: 'API Requests', ja: 'API Requests', ko: 'API Requests', ar: 'API Requests', de: 'API Requests', es: 'API Requests', fr: 'API Requests', hi: 'API Requests', it: 'API Requests', nl: 'API Requests', pl: 'API Requests', pt: 'API Requests', ru: 'API Requests', th: 'API Requests', tr: 'API Requests', vi: 'API Requests' },
  'detail.daily': { zh: '按日 Token 消耗', en: 'Daily Token Usage', ja: 'Daily Token Usage', ko: 'Daily Token Usage', ar: 'Daily Token Usage', de: 'Daily Token Usage', es: 'Daily Token Usage', fr: 'Daily Token Usage', hi: 'Daily Token Usage', it: 'Daily Token Usage', nl: 'Daily Token Usage', pl: 'Daily Token Usage', pt: 'Daily Token Usage', ru: 'Daily Token Usage', th: 'Daily Token Usage', tr: 'Daily Token Usage', vi: 'Daily Token Usage' },
  'detail.back': { zh: '返回主面板', en: 'Back to Dashboard', ja: 'Back to Dashboard', ko: 'Back to Dashboard', ar: 'Back to Dashboard', de: 'Back to Dashboard', es: 'Back to Dashboard', fr: 'Back to Dashboard', hi: 'Back to Dashboard', it: 'Back to Dashboard', nl: 'Back to Dashboard', pl: 'Back to Dashboard', pt: 'Back to Dashboard', ru: 'Back to Dashboard', th: 'Back to Dashboard', tr: 'Back to Dashboard', vi: 'Back to Dashboard' },

  // 导航
  'nav.refresh': { zh: '刷新', en: 'Refresh', ja: '更新', ko: '새로고침', ar: 'Refresh', de: 'Refresh', es: 'Refresh', fr: 'Refresh', hi: 'Refresh', it: 'Refresh', nl: 'Refresh', pl: 'Refresh', pt: 'Refresh', ru: 'Refresh', th: 'Refresh', tr: 'Refresh', vi: 'Refresh' },
  'nav.settings': { zh: '设置', en: 'Settings', ja: '設定', ko: '설정', ar: 'Settings', de: 'Settings', es: 'Settings', fr: 'Settings', hi: 'Settings', it: 'Settings', nl: 'Settings', pl: 'Settings', pt: 'Settings', ru: 'Settings', th: 'Settings', tr: 'Settings', vi: 'Settings' },
  'nav.close': { zh: '关闭', en: 'Close', ja: '閉じる', ko: '닫기', ar: 'Close', de: 'Close', es: 'Close', fr: 'Close', hi: 'Close', it: 'Close', nl: 'Close', pl: 'Close', pt: 'Close', ru: 'Close', th: 'Close', tr: 'Close', vi: 'Close' },

  // 语言
  'settings.language': { zh: '语言', en: 'Language', ja: '言語', ko: '언어', ar: 'Language', de: 'Language', es: 'Language', fr: 'Language', hi: 'Language', it: 'Language', nl: 'Language', pl: 'Language', pt: 'Language', ru: 'Language', th: 'Language', tr: 'Language', vi: 'Language' },
  'settings.language_desc': { zh: '选择界面显示语言。', en: 'Choose display language.', ja: '表示言語を選択してください。', ko: '표시 언어를 선택하세요.', ar: 'Choose display language.', de: 'Choose display language.', es: 'Choose display language.', fr: 'Choose display language.', hi: 'Choose display language.', it: 'Choose display language.', nl: 'Choose display language.', pl: 'Choose display language.', pt: 'Choose display language.', ru: 'Choose display language.', th: 'Choose display language.', tr: 'Choose display language.', vi: 'Choose display language.' },
};

let currentLang: Lang = 'zh';

export function setLang(lang: Lang) {
  currentLang = lang;
  try { localStorage.setItem('dsm-lang', lang); } catch {}
}

export function getLang(): Lang {
  return currentLang;
}

export function initLang() {
  try {
    const saved = localStorage.getItem('dsm-lang');
    if (saved === 'en' || saved === 'zh' || saved === 'ja' || saved === 'ko') currentLang = saved as Lang;
  } catch {}
}

export function t(key: string): string {
  const entry = translations[key];
  if (!entry) return key;
  return entry[currentLang] || entry['zh'] || key;
}
